#Numpy


	NumPy or Numeric Python is a package for computation on homogenous n-dimensional arrays.
	In numpy dimensions are called as axes.


	Why do we need NumPy? [when python lists are already there]

	we cannot perform operations on all the elements of two list directly.
	For example, we cannot multiply two lists directly we will have to do it element wise. 
	This is where the role of NumPy comes into play.




In [1]:
list1 = [1, 2, 3, 4 ,5, 6]
list2 = [10, 9, 8, 7, 6, 5]


print(list1*list2)

TypeError: ignored

In [2]:
import numpy as np

In [3]:
list1 = [1, 2, 3, 4, 5, 6] 
list2 = [10, 9, 8, 7, 6, 5] 
  
# Convert list1 into a NumPy array 
a1 = np.array(list1) 
  
# Convert list2 into a NumPy array 
a2 = np.array(list2) 
print(a1)
print(a2)
print(type(a1), type(a2))
print(a1*a2)

[1 2 3 4 5 6]
[10  9  8  7  6  5]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[10 18 24 28 30 30]


In [4]:
a1 + a2

array([11, 11, 11, 11, 11, 11])

In [5]:
a = np.array([1, 2, 3, 4, 5, 6], dtype = 'float')
print(a, a.dtype, a.ndim, a.shape)

a = np.array([1, 2, 3, 4, 5], dtype=np.float64)
print(a, a.dtype, a.ndim, a.shape)

a = np.zeros((2,4))
print(a)

b = np.empty((4,4))
print(b)

b = np.ones_like(a)
print(b)

[1. 2. 3. 4. 5. 6.] float64 1 (6,)
[1. 2. 3. 4. 5.] float64 1 (5,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[9.99653693e-317 3.80430547e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.50008929e+248 4.31174539e-096 9.80058441e+252]
 [1.23971686e+224 2.59031995e-144 6.06003395e+233 1.06400250e+248]
 [2.59050167e-144 5.22286946e-143 2.66023306e-312 0.00000000e+000]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
np.empty((3,3))

array([[9.9e-324, 2.5e-323, 3.5e-323],
       [2.0e-323, 2.5e-323, 2.5e-323],
       [1.5e-323, 3.0e-323, 4.4e-323]])

In [7]:
print(np.linspace(0, 10, 5)) # 0    2.5    5    7.5    10
print(np.arange(0, 10, 2)) # 0 2 4 6 8


a = np.arange(6)  
print(a, "np.arange")

b = np.arange(12).reshape(6,2) 
print("np.arange(12).reshape(4,3)")
print(b)

c = np.arange(24).reshape(2,3,4)
print("np.arange(24).reshape(2,3,4)")
print(c,c.ndim)


b = np.arange(12).reshape(3,4)
print("np.arange(12).reshape(3,4)")
print(b)


[ 0.   2.5  5.   7.5 10. ]
[0 2 4 6 8]
[0 1 2 3 4 5] np.arange
np.arange(12).reshape(4,3)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
np.arange(24).reshape(2,3,4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 3
np.arange(12).reshape(3,4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Indexing using index arrays

In [ ]:
a = np.array([2,5,7,4,5,5,3,6,9])
a[ [0,1,2] ]

array([2, 5, 7])

In [9]:
a = np.array([0,2,3,3,])
a[ [0,1,-2] ]

array([0, 2, 3])

In [10]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
print(b.sum(axis=1))                     # sum of each column

print(b.min(axis=0))                           # min of each row

[ 6 22 38]
[0 1 2 3]


In [12]:
a = np.arange(10)**3
print(a)
# array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])
print(a[-2])
# 8
print(a[2:6:2])
# array([ 8, 27, 64])
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
print(a)
# array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])
print(a[ : :-2])                                 # reversed a
# array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

[  0   1   8  27  64 125 216 343 512 729]
512
[ 8 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[729 343 125  27   1]


In [ ]:
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]])

print("Vertical stacking:", np.vstack((a, b)))  # 4,2
  
#horizontal stacking 
print("Horizontal stacking:", np.hstack((a, b))) # 
  
c = [5, 6] 
  
# stacking columns 
print("Column stacking:", np.column_stack((a, b)))



a = np.array([[1, 3, 5, 7, 9, 11], 
              [2, 4, 6, 8, 10, 12]]) 

print(a)
# horizontal splitting 
print("Splitting along horizontal axis into 3 parts:", np.hsplit(a, 3)) 
  
# vertical splitting 
print("Splitting along vertical axis into 2 parts:", np.vsplit(a, 2))


Vertical stacking: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stacking: [[1 2 5 6]
 [3 4 7 8]]
Column stacking: [[1 2 5 6]
 [3 4 7 8]]
[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]
Splitting along horizontal axis into 3 parts: [array([[1, 3],
       [2, 4]]), array([[5, 7],
       [6, 8]]), array([[ 9, 11],
       [10, 12]])]
Splitting along vertical axis into 2 parts: [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [ ]:
a = np.arange(20, 10, -1)  
print("sequential array with a negative step: ",a) 

sequential array with a negative step:  [20 19 18 17 16 15 14 13 12 11]


In [ ]:
a = np.arange(20, 10, -1)  
print("sequential array with a negative step: ",a) 
  
# Indexes are specified inside the np.array method. 
newnp = a[np.array([4, 3, 1, 2 ])] 
print(a)
print("Elements: ",newnp)

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) 
  
# Index values can be negative. 
arr = a[np.array([1, 3, -3])]
print("Elements: ", arr)

# [2 4 7]

sequential array with a negative step:  [20 19 18 17 16 15 14 13 12 11]
[20 19 18 17 16 15 14 13 12 11]
Elements:  [16 17 19 18]
Elements:  [2 4 7]


# numpy indexing and slicing

	There are three kinds of indexing available: 
		record access, basic slicing, advanced indexing.
		Which one occurs depends on object.

In [ ]:
import numpy as np
a = np.arange(20) 
print(a) 
  
# a[start:stop:step] 
print(a[-8:17:2])  
  
# The : operator means all elements till the end. 
print(a[10:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[12 14 16]
[10 11 12 13 14 15 16 17 18 19]


In [ ]:
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print(a[:, 0]) # single row with 0 index column value
print(a[:, 1])
print(a[:, 2])
print(a[0, :])
print(a[1, :])

print(a[0:2, 1:3]) # a[row, column]
print(a[0:2, 0:2])

[1 4 7]
[2 5 8]
[3 6 9]
[1 2 3]
[4 5 6]
[[2 3]
 [5 6]]
[[1 2]
 [4 5]]


In [ ]:
# np.random.seed(5)
vv = np.random.random((5, 4))
print(vv)

# print(vv[2:5, 1:2])
# print(vv[2:5, 1])
# print(vv[2:-1, :])

[[0.81464201 0.81028553 0.58937388 0.91473434]
 [0.05982164 0.96499664 0.57097522 0.30251811]
 [0.82570583 0.65941728 0.98650144 0.10748953]
 [0.58091853 0.47282816 0.65227079 0.24185905]
 [0.03113006 0.54423235 0.36471018 0.89233328]]


# Advanced indexing


	Purely integer indexing:
		When integers are used for indexing.
		Each element of first dimension is paired with the element of the second dimension


In [ ]:
a = np.array([[1 ,2 ],
              [3 ,4 ],
              [5 ,6 ]]) 
print(a[[0 , 2 ]])
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])

[[1 2]
 [5 6]]
[1 3 6]


In [ ]:
a = np.array([1,2,3,4,5,6,7])
a[[2,0,5,1]]

array([3, 1, 6, 2])

#Boolean Indexing

	
		This indexing has some boolean expression as the index. 
		Those elements are returned which satisfy that Boolean expression.
		It is used for filtering the desired element values.






In [13]:
a = np.array([10, 40, 80, 50, 100])
a [  [True, False, False,False, True]  ] 



array([ 10, 100])

In [15]:
a [ a>50 ]

array([ 80, 100])

In [ ]:
a = np.array([10, 40, 80, 50, 100]) 
b = a[a>=40]
b = b[b<=50]
b

array([40, 50])

numpy.ndarray

In [ ]:
a = np.array([10, 40]) 
a[ [False, True] ]

array([10, 40])

In [ ]:
import numpy as np

a = np.array([10, 40, 80, 50, 100]) 
print(a[a>50])


b = np.array([[5, 5],
              [15, 5],
              [16, 5]]) 

sumrow = b.sum(axis = 1) 

sumrow

[ 80 100]


array([10, 20, 21])

In [ ]:
print('Sumrow',sumrow)
print(b[sumrow%10==0])

Sumrow [10 20 21]
[[ 5  5]
 [15  5]]




```
a[start:end] # items start through end-1
a[start:]    # items start through the rest of the array
a[:end]      # items from the beginning through end-1
a[:]         # a copy of the whole array
# There is also the step value, which can be used with any of the above:
```



```
a[start:end:step] # start through not past end, by step


a[-1]    # last item in the array
a[-2:]   # last two items in the array
a[:-2]   # everything except the last two items
Similarly, step may be a negative number:

a[::-1]    # all items in the array, reversed
a[1::-1]   # the first two items, reversed
a[:-3:-1]  # the last two items, reversed
a[-3::-1]  # everything except the last two items, reversed
```



#File read from local computer

In [16]:
from google.colab import files
uploaded = files.upload()

Saving train.txt to train.txt


In [17]:
directory = '/content/train.txt'

In [20]:
import io
import pandas as pd
df = pd.read_csv(directory, sep=" ", header = None, names= [ 'A','B','C'])
print(df)

    A  B  C
0   2  2  1
1   3  1  1
2  -4  3  2
3   3  3  1
4  -1 -3  1
5   2  6  2
6   4  2  1
7  -2 -2  1
8   0  0  2
9  -2  2  2
10 -1 -1  2
11 -4  2  2


In [21]:
df.values

array([[ 2,  2,  1],
       [ 3,  1,  1],
       [-4,  3,  2],
       [ 3,  3,  1],
       [-1, -3,  1],
       [ 2,  6,  2],
       [ 4,  2,  1],
       [-2, -2,  1],
       [ 0,  0,  2],
       [-2,  2,  2],
       [-1, -1,  2],
       [-4,  2,  2]])

#File read from google drive

In [ ]:
main_directory  = '/content/drive/MyDrive/lab 2/train.txt'

df1 = pd.read_csv(main_directory, sep=" " , header = None, dtype = 'Int64')
print(df1)

     0   1  2
0    2   2  1
1    3   1  1
2   -4   3  2
3    3   3  1
4   -1  -3  1
5    2   6  2
6    4   2  1
7   -2  -2  1
8    0   0  2
9   -2   2  2
10  -1  -1  2
11  -4   2  2


In [23]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [28]:
a = pd.read_csv('/content/drive/MyDrive/lab 2/train.txt', header = None, names = ['A', 'B', 'C'], sep = ' ')
a

A  B  C
0   2  2  1
1   3  1  1
2  -4  3  2
3   3  3  1
4  -1 -3  1
5   2  6  2
6   4  2  1
7  -2 -2  1
8   0  0  2
9  -2  2  2
10 -1 -1  2
11 -4  2  2

In [29]:
a.to_csv('/content/drive/MyDrive/lab 2/newfile.csv', index = None)